language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
gemfile:
  - Gemfile
branches:
  only:
    - devel
env:
  global:
    - REDMINE_LANG=en
    - MYSQL_DATABASE=redmine
    - MYSQL_HOST=127.0.0.1
    - MYSQL_PORT=3306
    - MYSQL_USER=root
    - MYSQL_PASSWORD=
  matrix:
    - REDMINE_VERSION=2.5.2 DATABASE_ADAPTER=mysql
    - REDMINE_VERSION=2.5.2 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=2.5.1
    # - REDMINE_VERSION=2.5.0
    - REDMINE_VERSION=2.4.6 DATABASE_ADAPTER=mysql
    - REDMINE_VERSION=2.4.6 DATABASE_ADAPTER=postgresql
    # - REDMINE_VERSION=2.4.5
    # - REDMINE_VERSION=2.4.4
    # - REDMINE_VERSION=2.4.3
    # - REDMINE_VERSION=2.4.2
    # - REDMINE_VERSION=2.4.1
    # - REDMINE_VERSION=2.4.0
    # - REDMINE_VERSION=2.3.4
    # - REDMINE_VERSION=2.2.4
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libicu-dev libssh2-1 libssh2-1-dev cmake
  - cd ../..
  - ./jbox-web/redmine_git_hosting/contrib/travis/install_redmine.sh
  - cd redmine
  - echo $(pwd)
  - export BUNDLE_GEMFILE=$PWD/Gemfile
before_script:
  - echo $(pwd)
  - mysql -e 'create database redmine;'
  - psql -c 'create database redmine;' -U postgres
  - bundle exec rake generate_secret_token
  - bundle exec rake db:migrate
  - bundle exec rake redmine:load_default_data
  - bundle exec rake redmine:plugins:migrate
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake redmine_git_hosting:ci:all
